[[constraint]]
  name = "github.com/franela/goblin"
  version = "0.0.2"

[[constraint]]
  name = "github.com/gomicro/ledger"
  version = "0.1.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.4.2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[prune]
  go-tests = true
  unused-packages = true
