---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: recording-slo-devops-duty-rules
spec: 
  groups:
    - name: slo-sli-recordings-devops-duty-requests-availability
      rules:
        - record: slo:sli_error:ratio_increase5m
          expr: |
            sum(increase(http_server_requests_seconds_count{job="devops-duty", uri!~".*actuator.*", status=~"(5..|429)"}[5m]))
            /
            sum(increase(http_server_requests_seconds_count{job="devops-duty", uri!~".*actuator.*"}[5m]))
          labels:
            id: devops-duty-requests-availability
            service: devops-duty
            slo: requests-availability
            window: 5m
        - record: slo:sli_error:ratio_increase30m
          expr: |
            sum(increase(http_server_requests_seconds_count{job="devops-duty", uri!~".*actuator.*", status=~"(5..|429)"}[30m]))
            /
            sum(increase(http_server_requests_seconds_count{job="devops-duty", uri!~".*actuator.*"}[30m]))
          labels:
            id: devops-duty-requests-availability
            service: devops-duty
            slo: requests-availability
            window: 30m
        - record: slo:sli_error:ratio_increase1h
          expr: |
            sum(increase(http_server_requests_seconds_count{job="devops-duty", uri!~".*actuator.*", status=~"(5..|429)"}[1h]))
            /
            sum(increase(http_server_requests_seconds_count{job="devops-duty", uri!~".*actuator.*"}[1h]))
          labels:
            id: devops-duty-requests-availability
            service: devops-duty
            slo: requests-availability
            window: 1h
        - record: slo:sli_error:ratio_increase1d
          expr: |
            sum(increase(http_server_requests_seconds_count{job="devops-duty", uri!~".*actuator.*", status=~"(5..|429)"}[1d]))
            /
            sum(increase(http_server_requests_seconds_count{job="devops-duty", uri!~".*actuator.*"}[1d]))
          labels:
            id: devops-duty-requests-availability
            service: devops-duty
            slo: requests-availability
            window: 1d
        - record: slo:sli_error:ratio_increase3d
          expr: |
            sum(increase(http_server_requests_seconds_count{job="devops-duty", uri!~".*actuator.*", status=~"(5..|429)"}[3d]))
            /
            sum(increase(http_server_requests_seconds_count{job="devops-duty", uri!~".*actuator.*"}[3d]))
          labels:
            id: devops-duty-requests-availability
            service: devops-duty
            slo: requests-availability
            window: 3d
        - record: slo:sli_error:ratio_increase30d
          expr: |
            sum(increase(http_server_requests_seconds_count{job="devops-duty", uri!~".*actuator.*", status=~"(5..|429)"}[30d]))
            /
            sum(increase(http_server_requests_seconds_count{job="devops-duty", uri!~".*actuator.*"}[30d]))
          labels:
            id: devops-duty-requests-availability
            service: devops-duty
            slo: requests-availability
            window: 30d
    - name: slo-meta-recordings-devops-duty-requests-availability
      rules:
        - record: slo:objective:ratio
          expr: vector(0.990000000000000)
          labels:
            id: devops-duty-requests-availability
            service: devops-duty
            slo: requests-availability
        - record: slo:error_budget:ratio
          expr: vector(1-0.990000000000000)
          labels:
            id: devops-duty-requests-availability
            service: devops-duty
            slo: requests-availability
        - record: slo:time_period:days
          expr: vector(30)
          labels:
            id: devops-duty-requests-availability
            service: devops-duty
            slo: requests-availability
            window: 30d
        - record: slo:current_burn_rate:ratio
          expr: |
            slo:sli_error:ratio_increase5m{id="devops-duty-requests-availability", service="devops-duty", slo="requests-availability"}
            / on(id, slo, service) group_left
            slo:error_budget:ratio{id="devops-duty-requests-availability", service="devops-duty", slo="requests-availability"}
          labels:
            id: devops-duty-requests-availability
            service: devops-duty
            slo: requests-availability
            window: 5m
        - record: slo:period_burn_rate:ratio
          expr: |
            slo:sli_error:ratio_increase30d{id="devops-duty-requests-availability", service="devops-duty", slo="requests-availability"}
            / on(id, slo, service) group_left
            slo:error_budget:ratio{id="devops-duty-requests-availability", service="devops-duty", slo="requests-availability"}
          labels:
            id: devops-duty-requests-availability
            service: devops-duty
            slo: requests-availability
            window: 30d
        - record: slo:period_error_budget_remaining:ratio
          expr: 1 - slo:period_burn_rate:ratio{id="devops-duty-requests-availability", service="devops-duty", slo="requests-availability"}
          labels:
            id: devops-duty-requests-availability
            service: devops-duty
            slo: requests-availability
            window: 30d