---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: recording-slo-latency-duty-rules
spec: 
  groups:
    - name: slo-sli-recordings-duty-requests-latency
      rules:
        - record: slo:sli_error:ratio_increase5m
          # Number of requests that violated the latency SLO (all requests that took more than 500ms to be served)
          # /
          # Number of requests served in the SLO window
          expr: |
            (
              sum(increase(http_server_requests_seconds_bucket{job="duty", uri!~".*actuator.*", status=~"(5..|429)", le="0.5"}[5m]))
            )
            /
            (
              sum(increase(http_server_requests_seconds_count{job="duty", uri!~".*actuator.*"}[5m]))
            )
          labels:
            id: duty-requests-latency
            service: duty
            slo: requests-latency
            window: 5m
        - record: slo:sli_error:ratio_increase30m
          # Number of requests that violated the latency SLO (all requests that took more than 500ms to be served)
          # /
          # Number of requests served in the SLO window
          expr: |
            (
              sum(increase(http_server_requests_seconds_bucket{job="duty", uri!~".*actuator.*", status=~"(5..|429)", le="0.5"}[30m]))
            )
            /
            (
              sum(increase(http_server_requests_seconds_count{job="duty", uri!~".*actuator.*"}[30m]))
            )
          labels:
            id: duty-requests-latency
            service: duty
            slo: requests-latency
            window: 30m
        - record: slo:sli_error:ratio_increase1h
          # Number of requests that violated the latency SLO (all requests that took more than 500ms to be served)
          # /
          # Number of requests served in the SLO window
          expr: |
            (
              sum(increase(http_server_requests_seconds_bucket{job="duty", uri!~".*actuator.*", status=~"(5..|429)", le="0.5"}[1h]))
            )
            /
            (
              sum(increase(http_server_requests_seconds_count{job="duty", uri!~".*actuator.*"}[1h]))
            )
          labels:
            id: duty-requests-latency
            service: duty
            slo: requests-latency
            window: 1h
        - record: slo:sli_error:ratio_increase3d
          # Number of requests that violated the latency SLO (all requests that took more than 500ms to be served)
          # /
          # Number of requests served in the SLO window
          expr: |
            (
              sum(increase(http_server_requests_seconds_bucket{job="duty", uri!~".*actuator.*", status=~"(5..|429)", le="0.5"}[3d]))
            )
            /
            (
              sum(increase(http_server_requests_seconds_count{job="duty", uri!~".*actuator.*"}[3d]))
            )
          labels:
            id: duty-requests-latency
            service: duty
            slo: requests-latency
            window: 3d
        - record: slo:sli_error:ratio_increase30d
          expr: |
            (
              sum(increase(http_server_requests_seconds_bucket{job="duty", uri!~".*actuator.*", status=~"(5..|429)", le="0.5"}[30d]))
            )
            /
            (
              sum(increase(http_server_requests_seconds_count{job="duty", uri!~".*actuator.*"}[30d]))
            )
          labels:
            id: duty-requests-latency
            service: duty
            slo: requests-latency
            window: 30d
    - name: slo-meta-recordings-duty-requests-latency
      rules:
      - record: slo:objective:ratio
        expr: vector(0.95)
        labels:
          id: duty-requests-latency
          service: duty
          slo: requests-latency
      - record: slo:error_budget:ratio
        expr: vector(1-0.95)
        labels:
          id: duty-requests-latency
          service: duty
          slo: requests-latency
      - record: slo:time_period:days
        expr: vector(30)
        labels:
          id: duty-requests-latency
          service: duty
          slo: requests-latency
      - record: slo:current_burn_rate:ratio
        expr: |
          slo:sli_error:ratio_increase5m{id="duty-requests-latency", service="duty", slo="requests-latency"}
          / on(id, slo, service) group_left
          slo:error_budget:ratio{id="duty-requests-latency", service="duty", slo="requests-latency"}
        labels:
          id: duty-requests-latency
          service: duty
          slo: requests-latency
      - record: slo:period_burn_rate:ratio
        expr: |
          slo:sli_error:ratio_increase30d{id="duty-requests-latency", service="duty", slo="requests-latency"}
          / on(id, slo, service) group_left
          slo:error_budget:ratio{id="duty-requests-latency", service="duty", slo="requests-latency"}
        labels:
          id: duty-requests-latency
          service: duty
          slo: requests-latency
      - record: slo:period_error_budget_remaining:ratio
        expr: 1 - slo:period_burn_rate:ratio{id="duty-requests-latency",
          service="duty", slo="requests-latency"}
        labels:
          id: duty-requests-latency
          service: duty
          slo: requests-latency
