---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yaml
  - service.yaml

transformers:
  - commonLabelTransformer.yaml

configMapGenerator:
  - name: duty-rules-configmap
    files:
      - rules/duty.yaml
      - rules/foo.json
      - rules/notfound.json
      - rules/unauthorized.json

generatorOptions:
  disableNameSuffixHash: true