---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yaml
  - service.yaml
  - servicemonitor.yaml
  - ./rules/slo/recording-slo-availability-duty.yaml
  - ./rules/slo/recording-slo-latency-duty.yaml
  - ./rules/alerts/slo-duty.yaml

transformers:
  - commonLabelTransformer.yaml

configMapGenerator:
  - name: duty-rules-configmap
    files:
      - rules/duty.yaml
      - rules/foo.json
      - rules/notfound.json
      - rules/unauthorized.json
      - rules/internalserver.json

generatorOptions:
  disableNameSuffixHash: true