---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-monitoring-duty
spec:
  jobLabel: devops-monitoring-duty
  selector:
    matchLabels:
      app.kubernetes.io/component: mock
      app.kubernetes.io/name: duty
  namespaceSelector:
    matchNames:
      - ""
  endpoints:
    - port: actuator
      interval: 15s
      path: "/prometheus"
      scheme: http