---
status: "foo"
routes:
  - endpoint: "/v1/foo"
    response:
      code: 200
      payload: "config/foo.json"
  - endpoint: "/v1/bar"
    response:
      code: 401
      payload: "config/unauthorized.json"
